version: '3.0'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bank_server
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE_DOCKER=postgresql://postgres:123456@db:5432/bank_server?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

#http://prometheus:9090, conectar no grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    #depends_on: 
    #  - cadvisor
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

#password admin admin
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    depends_on:
      - prometheus