// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Account struct {
	ID        string
	Owner     string
	Balance   int64
	CreatedAt time.Time
}

type Entry struct {
	ID              string
	AccountID       string
	TransactionType string
	Amount          int64
	CreatedAt       time.Time
}

type Transfer struct {
	ID            string
	FromAccountID string
	ToAccountID   string
	Amount        int64
	CreatedAt     time.Time
}

type User struct {
	Username  string
	Email     string
	CreatedAt time.Time
}
